### ISSUE TITLE
MVP pattern

### ISSUE THREAD

**Issue by FromSi** [quaap/BookyMcBookface#28]
Did you ever think of rewriting the project into an **MVP** pattern?
Your code is too unreadable =(
![image](https://user-images.githubusercontent.com/22871855/43999534-c894f40a-9e2f-11e8-8860-71ebf40d040f.png)

**Comment by quaap** [comment]
Yeah, trust me, I know.   I generally start these things without knowing how it's going to work, and add bits until it's functional.  I don't have a lot of child-free time to devote to programming right now, so I use my time to add features instead of going back to clean things up and re-organize.  I would love to properly separate out logic from presentation... maybe someday.
