### ISSUE TITLE
Dragging up or down causes text selection to appear and disappear

### ISSUE THREAD

**Issue by quaap** [quaap/BookyMcBookface#3]
On some devices, doing sub-page scrolling by dragging causes the android "text selected" controls to repeatedly appear and disappear.   This is harmless but annoying.

**Comment by wshanks** [comment]
Is this issue Android version dependent? I use BookyMcBookface on an old Android 7 device and find that it is perfect for reading books there -- just enough features to let you read without any cruft. However, I almost gave up on the app when I first tried it because the text selection behavior was so annoying. I discovered that if I disabled page scrolling and only had drag scrolling selected that the annoying text selection went away.

If the annoying behavior is not present on newer devices, perhaps an entry could be added to the known issues list? If it is present on newer devices, maybe page scrolling should not be on by default?
